---
- hosts: k8s_worker
  become: true
  tasks:
    - name: Reset kubeadm
      shell: kubeadm reset --force

    - name: Join the cluster
      shell: "{{ hostvars['kubeadm_join_command']['joincmd'] }}"
