---
- hosts: k8s_master
  tasks:
    - name: Verify that workers have joined
      shell: kubectl get nodes
      register: kubectl_output
    
    - name: Print worker nodes
      debug:
        msg: "{{ kubectl_output.stdout }}"
