---
- hosts: k8s_master
  tasks:
    - name: "Set up network bridge: bridge-nf-call-iptables"
      ansible.posix.sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: '1'

    - name: Reset kubeadm
      become: true
      shell: kubeadm reset --force

    - name: Init kubeadm
      become: true
      shell: kubeadm init

    - name: Create .kube directory
      file:
        path: /home/ubuntu/.kube
        state: directory
        mode: '0755'

    - name: Copy default configuration file over
      become: true
      copy:
        remote_src: true
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        owner: "{{ ansible_ssh_user }}"
        group: "{{ ansible_ssh_user }}"
        mode: '0644'
      
    - name: Chown the .kube directory
      shell: sudo chown -R $USER $HOME/.kube

    - name: Install Weave Net addon
      shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

    - name: Allow master to schedule pods
      shell: kubectl taint nodes --all node-role.kubernetes.io/master-

    - name: Print kubeadm join command
      shell: kubeadm token create --print-join-command
      register: kubeadm_output

    - name: Store the join command in a cross-host variable
      add_host:
        name: "kubeadm_join_command"
        joincmd: "{{ kubeadm_output.stdout }}"
